DEF_WIDTH: 640
DEF_HEIGHT: 480
FPS: 30
VERTEX_COUNT: 32
DEEP_DARK_FANTASIES: [-2, 8]
VERTEX_ROUND_RADIUS_RANGE: [8, 96]
SPEED_RANGE: [-0.01, 0.01]
MAX_NORMAL_DISTANCE: 240
LIGHT_RANGE: [0, 128]

isFullScreen: False
isDarkTheme: True
isDebug: True